pygments: true
auto: true

server_port: 4001

title: Nimeregister!
url: http://nimeregister.coom

claim: Join us! Find your nearest registration centre and spread the word. Mimi Nimeregister, je wewe?

author :
  name : David Lemayian
  email : david@on.co.ke
  github : http://github.com/DavidLemayian
  twitter : @DavidLemayian